/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from;
 */

#ifndef	_SYS_RT_SYSCALL_H_
#define	_SYS_RT_SYSCALL_H_

#define	SYS_rt_memlk	0
#define	SYS_rt_memunlk	1
#define	SYS_rt_psx4_get_todtimer	2
#define	SYS_rt_psx4_set_todtimer	3
#define	SYS_rt_psx4_time_drift	4
#define	SYS_rt_rt_getprio	5
#define	SYS_rt_rt_setprio	6
#define	SYS_rt_psx4_timer_create	7
#define	SYS_rt_psx4_timer_delete	8
#define	SYS_rt_psx4_sem_sleep	9
#define	SYS_rt_psx4_sem_wakeup	10
#define	SYS_rt_aio_init	11
#define	SYS_rt_aio_transfer_old	12
#define	SYS_rt_aio_transfer_done	13
				/* 14 is obsolete aio_wait_d11 */
#define	SYS_rt_aio_done	15
#define	SYS_rt_aio_transfer_cancel	16
#define	SYS_rt_aio_info	17
#define	SYS_rt_psx4_ipc_snd_sleep	18
#define	SYS_rt_psx4_ipc_rcv_sleep	19
#define	SYS_rt_psx4_ipc_wakeup_sender	20
#define	SYS_rt_psx4_ipc_wakeup_receiver	21
#define	SYS_rt_psx4_csem_sleep_wakeup	22
#define	SYS_rt_aio_wait	23
#define	SYS_rt_aioinit_lock_sleep	24
#define	SYS_rt_aioinit_lock_wakeup	25
#define	SYS_rt_psx4_ipc_notify	26
#define	SYS_rt_psx4_sigqueue	27
#define	SYS_rt_psx4_timer_overrun	28
#define	SYS_rt_aio_transfer	29
#define	SYS_rt_aio_group_init	30
#define	SYS_rt_aio_group_info	31

#define	rt_FIRST	0
#define	rt_LAST	31

#endif	/* _SYS_RT_SYSCALL_H_ */
