/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from; 
 */

#ifndef	_SYS_SOE_TWO_SYSCALL_H_
#define	_SYS_SOE_TWO_SYSCALL_H_

#define	SYS_soe_two_nosys	0

#define	soe_two_FIRST	0
#define	soe_two_LAST	0

#endif	/* _SYS_SOE_TWO_SYSCALL_H_ */
