/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from; 
 */

#ifndef	_SYS_SVID_THREE_SYSCALL_H_
#define	_SYS_SVID_THREE_SYSCALL_H_

#define	SYS_svid_three_nosys	0

#define	svid_three_FIRST	0
#define	svid_three_LAST	0

#endif	/* _SYS_SVID_THREE_SYSCALL_H_ */
