/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from; 
 */

#ifndef	_SYS_SVR_FOUR_SYSCALL_H_
#define	_SYS_SVR_FOUR_SYSCALL_H_

#define	SYS_svr_four_nosys	0

#define	svr_four_FIRST	0
#define	svr_four_LAST	0

#endif	/* _SYS_SVR_FOUR_SYSCALL_H_ */
