/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from; 
 */

#ifndef	_SYS_SYSCALL_H_
#define	_SYS_SYSCALL_H_

#define	SYS_syscall	0
#define	SYS_exit	1
#define	SYS_fork	2
#define	SYS_read	3
#define	SYS_write	4
#define	SYS_old_open	5	/* 5 is old open */
#define	SYS_close	6
#define	SYS_wait4	7
#define	SYS_old_creat	8	/* 8 is old creat */
#define	SYS_link	9
#define	SYS_unlink	10
#define	SYS_execv	11
#define	SYS_chdir	12
#define	SYS_fchdir	13
#define	SYS_mknod	14
#define	SYS_chmod	15
#define	SYS_chown	16
#define	SYS_obreak	17
#define	SYS_pre_F64_getfsstat	18
#define	SYS_lseek	19
#define	SYS_getpid	20
#define	SYS_mount	21
#define	SYS_unmount	22
#define	SYS_setuid	23
#define	SYS_getuid	24
#define	SYS_exec_with_loader	25
#define	SYS_ptrace	26
#ifdef	COMPAT_43
#define	SYS_nrecvmsg	27
#define	SYS_nsendmsg	28
#define	SYS_nrecvfrom	29
#define	SYS_naccept	30
#define	SYS_ngetpeername	31
#define	SYS_ngetsockname	32
#else
#define	SYS_recvmsg	27
#define	SYS_sendmsg	28
#define	SYS_recvfrom	29
#define	SYS_accept	30
#define	SYS_getpeername	31
#define	SYS_getsockname	32
#endif
#define	SYS_access	33
#define	SYS_chflags	34
#define	SYS_fchflags	35
#define	SYS_sync	36
#define	SYS_kill	37
#define	SYS_old_stat	38	/* 38 is old stat */
#define	SYS_setpgid	39
#define	SYS_old_lstat	40	/* 40 is old lstat */
#define	SYS_dup	41
#define	SYS_pipe	42
#define	SYS_set_program_attributes	43
#define	SYS_profil	44
#define	SYS_open	45
				/* 46 is obsolete osigaction */
#define	SYS_getgid	47
#define	SYS_sigprocmask	48
#define	SYS_getlogin	49
#define	SYS_setlogin	50
#define	SYS_acct	51
#define	SYS_sigpending	52
#define	SYS_classcntl	53
#define	SYS_ioctl	54
#define	SYS_reboot	55
#define	SYS_revoke	56
#define	SYS_symlink	57
#define	SYS_readlink	58
#define	SYS_execve	59
#define	SYS_umask	60
#define	SYS_chroot	61
#define	SYS_old_fstat	62	/* 62 is old fstat */
#define	SYS_getpgrp	63
#define	SYS_getpagesize	64
#define	SYS_mremap	65
#define	SYS_vfork	66
#define	SYS_pre_F64_stat	67
#define	SYS_pre_F64_lstat	68
#define	SYS_sbrk	69
#define	SYS_sstk	70
#define	SYS_mmap	71
#define	SYS_ovadvise	72
#define	SYS_munmap	73
#define	SYS_mprotect	74
#define	SYS_madvise	75
#define	SYS_old_vhangup	76	/* 76 is old vhangup */
#define	SYS_kmodcall	77
#define	SYS_mincore	78
#define	SYS_getgroups	79
#define	SYS_setgroups	80
#define	SYS_old_getpgrp	81	/* 81 is old getpgrp */
#define	SYS_setpgrp	82
#define	SYS_setitimer	83
#define	SYS_old_wait	84	/* 84 is old wait */
#define	SYS_table	85
#define	SYS_getitimer	86
#define	SYS_gethostname	87
#define	SYS_sethostname	88
#define	SYS_getdtablesize	89
#define	SYS_dup2	90
#define	SYS_pre_F64_fstat	91
#define	SYS_fcntl	92
#define	SYS_select	93
#define	SYS_poll	94
#define	SYS_fsync	95
#define	SYS_setpriority	96
#define	SYS_socket	97
#define	SYS_connect	98
#ifdef	COMPAT_43
#define	SYS_accept	99
#else
#define	SYS_old_accept	99	/* 99 is old accept */
#endif
#define	SYS_getpriority	100
#ifdef	COMPAT_43
#define	SYS_send	101
#define	SYS_recv	102
#else
#define	SYS_old_send	101	/* 101 is old send */
#define	SYS_old_recv	102	/* 102 is old recv */
#endif
#define	SYS_sigreturn	103
#define	SYS_bind	104
#define	SYS_setsockopt	105
#define	SYS_listen	106
#define	SYS_plock	107
#define	SYS_old_sigvec	108	/* 108 is old sigvec */
#define	SYS_old_sigblock	109	/* 109 is old sigblock */
#define	SYS_old_sigsetmask	110	/* 110 is old sigsetmask */
#define	SYS_sigsuspend	111
#define	SYS_sigstack	112
#ifdef	COMPAT_43
#define	SYS_recvmsg	113
#define	SYS_sendmsg	114
#else
#define	SYS_old_recvmsg	113	/* 113 is old recvmsg */
#define	SYS_old_sendmsg	114	/* 114 is old sendmsg */
#endif
				/* 115 is obsolete vtrace */
#define	SYS_gettimeofday	116
#define	SYS_getrusage	117
#define	SYS_getsockopt	118
#define	SYS_numa_syscalls	119
#define	SYS_readv	120
#define	SYS_writev	121
#define	SYS_settimeofday	122
#define	SYS_fchown	123
#define	SYS_fchmod	124
#ifdef	COMPAT_43
#define	SYS_recvfrom	125
#else
#define	SYS_old_recvfrom	125	/* 125 is old recvfrom */
#endif
#define	SYS_setreuid	126
#define	SYS_setregid	127
#define	SYS_rename	128
#define	SYS_truncate	129
#define	SYS_ftruncate	130
#define	SYS_flock	131
#define	SYS_setgid	132
#define	SYS_sendto	133
#define	SYS_shutdown	134
#define	SYS_socketpair	135
#define	SYS_mkdir	136
#define	SYS_rmdir	137
#define	SYS_utimes	138
				/* 139 is obsolete 4.2 sigreturn */
#define	SYS_adjtime	140
#ifdef	COMPAT_43
#define	SYS_getpeername	141
#else
#define	SYS_old_getpeername	141	/* 141 is old getpeername */
#endif
#define	SYS_gethostid	142
#define	SYS_sethostid	143
#define	SYS_getrlimit	144
#define	SYS_setrlimit	145
#define	SYS_old_killpg	146	/* 146 is old killpg */
#define	SYS_setsid	147
#define	SYS_quotactl	148
#define	SYS_oldquota	149
#ifdef	COMPAT_43
#define	SYS_getsockname	150
#else
#define	SYS_old_getsockname	150	/* 150 is old getsockname */
#endif
#define	SYS_pread	151
#define	SYS_pwrite	152
#define	SYS_pid_block	153
#define	SYS_pid_unblock	154
#define	SYS_signal_urti	155
#define	SYS_sigaction	156
#define	SYS_sigwaitprim	157
#define	SYS_nfssvc	158
#define	SYS_getdirentries	159
#define	SYS_pre_F64_statfs	160
#define	SYS_pre_F64_fstatfs	161
#define	SYS_freezefs	162
#define	SYS_async_daemon	163
#define	SYS_getfh	164
#define	SYS_getdomainname	165
#define	SYS_setdomainname	166
#define	SYS_exportfs	169
#define	SYS_alt_plock	181	/* 181 is alternate plock */
#define	SYS_getmnt	184
#define	SYS_alt_sigpending	187	/* 187 is alternate sigpending */
#define	SYS_alt_setsid	188	/* 188 is alternate setsid */
#define	SYS_swapon	199
#define	SYS_msgctl	200
#define	SYS_msgget	201
#define	SYS_msgrcv	202
#define	SYS_msgsnd	203
#define	SYS_semctl	204
#define	SYS_semget	205
#define	SYS_semop	206
#define	SYS_uname	207
#define	SYS_lchown	208
#define	SYS_shmat	209
#define	SYS_shmctl	210
#define	SYS_shmdt	211
#define	SYS_shmget	212
#define	SYS_mvalid	213
#define	SYS_getaddressconf	214
#define	SYS_msleep	215
#define	SYS_mwakeup	216
#define	SYS_msync	217
#define	SYS_signal	218
#define	SYS_utc_gettime	219
#define	SYS_utc_adjtime	220
#define	SYS_security	222
#define	SYS_kloadcall	223
#define	SYS_stat	224
#define	SYS_lstat	225
#define	SYS_fstat	226
#define	SYS_statfs	227
#define	SYS_fstatfs	228
#define	SYS_getfsstat	229
#define	SYS_gettimeofday64	230
#define	SYS_settimeofday64	231
#define	SYS_getpgid	233
#define	SYS_getsid	234
#define	SYS_sigaltstack	235
#define	SYS_waitid	236
#define	SYS_priocntlset	237
#define	SYS_sigsendset	238
#define	SYS_set_speculative	239
#define	SYS_msfs_syscall	240
#define	SYS_sysinfo	241
#define	SYS_uadmin	242
#define	SYS_fuser	243
#define	SYS_proplist_syscall	244
#define	SYS_ntp_adjtime	245
#define	SYS_ntp_gettime	246
#define	SYS_pathconf	247
#define	SYS_fpathconf	248
#define	SYS_sync2	249
#define	SYS_uswitch	250
#define	SYS_usleep_thread	251
#define	SYS_audcntl	252
#define	SYS_audgen	253
#define	SYS_sysfs	254
#define	SYS_subsys_info	255
#define	SYS_getsysinfo	256
#define	SYS_setsysinfo	257
#define	SYS_afs_syscall	258
#define	SYS_swapctl	259
#define	SYS_memcntl	260
#define	SYS_fdatasync	261
#define	SYS_oflock	262
#define	SYS__F64_readv	263
#define	SYS__F64_writev	264
#define	SYS_cdslxlate	265
#define	SYS_sendfile	266

#define	FIRST	0
#define	LAST	266

#endif	/* _SYS_SYSCALL_H_ */
