/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from; 
 */

#ifndef	_SYS_SYSV_SYSCALL_H_
#define	_SYS_SYSV_SYSCALL_H_

#define	SYS_sysv_unlink	0
#define	SYS_sysv_open	1
#define	SYS_sysv_waitpid	2

#define	sysv_FIRST	0
#define	sysv_LAST	2

#endif	/* _SYS_SYSV_SYSCALL_H_ */
