/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from; 
 */

#ifndef	_SYS_ULT_SYSCALL_H_
#define	_SYS_ULT_SYSCALL_H_

#define	SYS_ult_syscall	0

#define	ult_FIRST	0
#define	ult_LAST	0

#endif	/* _SYS_ULT_SYSCALL_H_ */
